### ISSUE TITLE
Ontology: Repeated SecurityFeatures field in "SecurityAdvisoryDocument"

### ISSUE THREAD

**Issue by lebogg** [clouditor/clouditor#1440]
SecurityFeatures occurring in all document objects bothers me, e.g. in SecurityAdvisoryDocument (see L1759):
 https://github.com/clouditor/clouditor/blob/43850bf7cbee00d2fa19967c46d6b41513f36559/api/ontology/ontology.proto#L1744-L1759

This is wrong, isn't it? Or did I miss sth?

**Comment by oxisto** [comment]
It’s not wrong. We also need this in further emerald discussion, because a document could describe a security feature. We could even use this in CSAF because you have these additional files that contain signature and hashes and therefore we could say that they offer the security feature „Integrity“.
