### ISSUE TITLE
Update version in OpenAPI specificiation files

### ISSUE THREAD

**Issue by fwendland** [clouditor/clouditor#759]
**Is your feature request related to a problem? Please describe.**
We're pulling the OpenAPI specification for the different Clouditor components into another project. Currently, it's quite difficult for us to determine whether a new version is available as the version stays fixed at `0.0.1`.

**Describe the solution you'd like**
Update the version within the OpenAPI specification if changes in the API occur.

**Describe alternatives you've considered**
1. Check if there have been GitHub commits since the last update (when I remeber, when the last update was).
2. Just copy over the file from GitHub, regardless of possible changes.

**Additional context**
OpenAPI specs
- openapi/assessment/openapi.yaml
- openapi/evidence/openapi.yaml
- openapi/orchestrator/openapi.yaml

**Comment by oxisto** [comment]
It's not that easy since updating it manually would result in a lot of work and probably divert from the real version over time. We could look into whether we set the version to `0.0.0` during development and have a special step in the GitHub CI for tagged commits (aka releases) that sets the correct version during the CI build and attaches them to the release.
